services:
  db-local:
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: elaut
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elaut"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
