#changesetBaseRefs:
#  - HEAD
#
#nmMode: hardlinks-global
#
#nmSelfReferences: false
#
nodeLinker: node-modules
#
#plugins:
#  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#    spec: "@yarnpkg/plugin-workspace-tools"
#  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
#    spec: "@yarnpkg/plugin-version"

#yarnPath: .yarn/releases/yarn-4.6.0.cjs

#nmHoistingLimits: workspaces
#nmMode: hardlinks-global
